# OpenCV for Pythonのチュートリアル解説

ここでは、OpenCVのドキュメントに書いてあるチュートリアルを実践します。  
https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html  
このJupyterLabのファイルはGitHub上で公開しています。  
https://github.com/okuokuch/Training_openCV_for_python

## 前提条件
1. Pythonの基礎技術
    1. 基本文法(if文、データ型、コメントアウト etc.)
    1. 組み込み関数(print, len, type etc.)
    1. 演算子(+, *, /, != etc.)
1. ライブラリのインストール(CV2,Numpy etr.)
1. JupyterLabを使用  
基本知識や環境構築に関して自分で行ってください  
以下に勉強になる関連リンクを添付しました。  

本取り組みの作成者おくおくは、Anaconda3にて環境構築しています。

基本文法に関するリンク  
https://www.sejuku.net/blog/49951  

上記で不明な点があれば、キーワードを拾ってググってみてください。

## Gui Features in OpenCV

ここでは、Gui Features in OpenCVルのうち以下項目の実践をします。
* Getting Started with Images
* Drawing Functions in OpenCV
* Mouse as a Paint-Brush
* Trackbar as the Color Palette

### Getting Started with Images
この項目では以下5つの関数の説明をします。
* imread
* imshow
* waitKey
* destroyAllwindows
* imwrite

チュートリアルURL  
https://docs.opencv.org/4.x/db/deb/tutorial_display_image.html   
関数URL  
https://docs.opencv.org/4.x/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56  
https://docs.opencv.org/4.x/d7/dfc/group__highgui.html#ga5628525ad33f52eab17feebcfba38bd7

#### <span style="color: red; ">**cv2.imread("ファイル名",[読み取り方])**<span>
**画像ファイルの読み込み**  
ファイル名は文字列で指定。  
読み取り方はドキュメント参照。  
* カラー
* 白黒
* 透明度込み
など

#### <span style="color: red; ">**cv2.imshow("表示名",表示したい変数)**</span>
**画像ファイルの表示**  
表示名は文字列で指定。  
表示名はWindowのタグ部分に表示される。

#### <span style="color: red; ">**cv2.waitKey(数字(int型))**</span>
**処理の中断**  
数字は整数(int型)を入れる。  
数字ミリ秒の間windowが表示される。  
waitKeyを設定しないと、図が表示されて一瞬で消えるのでimshowの結果を見ることができない。  
waitKey(0)とすると、キーボード入力された場合に消える設定。  
数字は負の整数でも0の時と同様の挙動。

#### <span style="color: red; ">**cv2.destroyAllWindows()**</span>
**表示中のすべてのwindwoを削除**

#### <span style="color: red; ">**cv2.imwrite("保存ファイル名",保存したい変数,[フォーマット指定])**</span>
**画像ファイルを保存**  
保存ファイル名は文字列で指定。  
保存したい変数に画像の変数を指定。  
フォーマット指定では、エンコード関係の設定。

In [6]:
import cv2
import numpy as np

In [7]:
img=cv2.imread("template_img\\python.png")

In [3]:
gray=cv2.imread("template_img\\python.png",cv2.IMREAD_GRAYSCALE)

In [10]:
gray2=cv2.imread("template_img\\opencv.png",cv2.IMREAD_GRAYSCALE)

In [9]:
cv2.imshow("python",img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
cv2.imwrite("template_img\\python_gray.png",gray)

True

### Drawing Functions in OpenCV  
この章では、図形を描写する関数を紹介します。  
紹介する関数は以下です。
* line
* rectangle
* arrowedLine
* circle
* Ellipse
* Polygon
* putText

チュートリアルURL  
https://docs.opencv.org/4.x/dc/da5/tutorial_py_drawing_functions.html  
関数URL  
https://docs.opencv.org/4.x/d6/d6e/group__imgproc__draw.html#gac865734d137287c0afb7682ff7b3db23

#### <span style="color: red; ">**cv2.line(画像変数,始点,終点,色,[線幅],[ライン種類],[分数bit])**<span>
**画像変数に直線を描写**  
始点、終点はタプル(x,y)で指定。  
色は(B,R,G)で指定。各色は0~255で指定。  
線幅は1以上の整数を指定。  
ライン種類は線の境目の種類。  
分数bitは、0以上の整数を記入。始点、終点の座標値が2^分数bit乗される。  
例) 0なら同じ位置、1なら全部半分の値、2なら1/4の値

#### <span style="color: red; ">**cv2.rectangle(画像変数,頂点1,頂点2,色,[線幅],[ライン種類],[分数bit])**<span>
**画像変数に四角形を描写**  
頂点1、頂点2はタプル(x,y)で指定。  
色は(B,R,G)で指定。各色は0~255で指定。  
線幅は1以上の整数の場合、枠線の太さ。負の整数を記入した場合、中塗りの四角形。  
ライン種類は線の境目の種類。  
分数bitは、0以上の整数を記入。始点、終点の座標値が2^分数bit乗される。  
例) 0なら同じ位置、1なら全部半分の値、2なら1/4の値

#### <span style="color: red; ">**cv2.arrowedLine(画像変数,頂点1,頂点2,色,[線幅],[ライン種類],[分数bit],[矢印の大きさ])**<span>
**画像変数に矢印線を描写**  
頂点1、頂点2はタプル(x,y)で指定。  
色は(B,R,G)で指定。各色は0~255で指定。  
線幅は1以上の整数を指定  
ライン種類は線の境目の種類。  
分数bitは、0以上の整数を記入。始点、終点の座標値が2^分数bit乗される。  
例) 0なら同じ位置、1なら全部半分の値、2なら1/4の値  
矢印の大きさは、矢印の長さとの相関を小数で指定。

#### <span style="color: red; ">**cv2.circle(画像変数,中心,半径,色,[線幅],[ライン種類],[分数bit])**<span>
**画像変数に円を描写**  
中心はタプル(x,y)で指定。  
半径は整数で指定。  
色は(B,R,G)で指定。各色は0~255で指定。  
線幅は1以上の整数の場合、枠線の太さ。負の整数を記入した場合、中塗りの円。  
ライン種類は線の境目の種類。  
分数bitは、0以上の整数を記入。始点、終点の座標値が2^分数bit乗される。  
例) 0なら同じ位置、1なら全部半分の値、2なら1/4の値  

#### <span style="color: red; ">**cv2.ellipse(画像変数,中心,軸の長さ,角度,開始角度,終了角度,色,[線幅],[ライン種類],[分数bit])**<span>
**画像変数に楕円を描写**  
中心はタプル(x,y)で指定。  
軸の長さは(長軸の半分,短軸の半分)で指定。  
角度は長軸を時計回りで回転させる角度を小数で指定。  
開始角度、終了角度は楕円を描く部分を小数で指定。  
色は(B,R,G)で指定。各色は0~255で指定。  
線幅は1以上の整数の場合、枠線の太さ。負の整数を記入した場合、中塗りの楕円。  
ライン種類は線の境目の種類。  
分数bitは、0以上の整数を記入。始点、終点の座標値が2^分数bit乗される。  
例) 0なら同じ位置、1なら全部半分の値、2なら1/4の値  

#### <span style="color: red; ">**cv2.polylines(画像変数,頂点の配列,曲線を閉じるか,色,[線幅],[ライン種類],[分数bit])**<span>
**画像変数に多角形を描写**  
頂点の配列にはrows×1×2となる形式で配列を指定。詳細は動画で解説。  
曲線を閉じるかをTrueにした場合、始点と終点の頂点を結ぶ線が引かれる。  
色は(B,R,G)で指定。各色は0~255で指定。  
線幅は1以上の整数。 
ライン種類は線の境目の種類。  
分数bitは、0以上の整数を記入。始点、終点の座標値が2^分数bit乗される。  
例) 0なら同じ位置、1なら全部半分の値、2なら1/4の値  

#### <span style="color: red; ">**cv2.putText(画像変数,テキスト,左下の位置,フォント,フォントサイズの倍率,色,[太さ],[ライン種類],[原点位置])**<span>
**画像変数に文字を描写**  
テキストに文字列を記入""で囲む。
文字の左下が原点位置。    
フォントはHersheyFontsから選べるが、<span style="color: red; ">日本語は表示不可</span>。  
フォントサイズの倍率は少数で指定。
色は(B,R,G)で指定。各色は0~255で指定。  
線幅は1以上の整数。 
ライン種類は線の境目の種類。  
原点位置がTrueなら左下が原点、Falseなら右上が原点となる。  

In [24]:
img=np.zeros((500,500,3),np.uint8)
img[:]=255
print(img)
cv2.imshow("test",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [89]:
img=np.zeros((500,500,3),np.uint8)
img[:]=255

cv2.line(img,(0,0),(200,100),(255,0,0),4,shift=0)
cv2.line(img,(100,0),(200,100),(0,255,0),5,shift=2)
cv2.rectangle(img,(300,200),(100,10),(0,0,255),-1)
cv2.arrowedLine(img,(400,0),(300,300),(255,0,0),2,tipLength=0.05)
cv2.circle(img,(200,200),50,(0,0,0),-1)
cv2.ellipse(img,(250,250),(100,50),0,45,225,(255,0,255),-1)
pts = np.array([[350,220],[400,235],[350,250],[150,80]], np.int32)
pts=pts.reshape((-1,1,2))
cv2.fillPoly(img,[pts],(0,0,0))
cv2.putText(img,"by okuoku",(100,430),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,0),2)
cv2.imshow("test",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

ミズゴロウの図

In [90]:
img=np.zeros((512,512,3),np.uint8)
img[:]=255
pts = np.array([[350,220],[400,235],[350,250]], np.int32)
pts = pts.reshape((-1,1,2))
cv2.fillPoly(img,[pts],(10,80,160))
pts2 = np.array([[350,245],[400,260],[350,275]], np.int32)
pts2 = pts2.reshape((-1,1,2))
cv2.fillPoly(img,[pts2],(10,80,160))
pts3 = np.array([[350,270],[400,285],[350,300]], np.int32)
pts3 = pts3.reshape((-1,1,2))
cv2.fillPoly(img,[pts3],(10,80,160))
pts4 = np.array([[158,220],[108,235],[158,250]], np.int32)
pts4 = pts4.reshape((-1,1,2))
cv2.fillPoly(img,[pts4],(10,80,160))
pts5 = np.array([[158,245],[108,260],[158,275]], np.int32)
pts5 = pts5.reshape((-1,1,2))
cv2.fillPoly(img,[pts5],(10,80,160))
pts6 = np.array([[158,270],[108,285],[158,300]], np.int32)
pts6 = pts6.reshape((-1,1,2))
cv2.fillPoly(img,[pts6],(10,80,160))
cv2.ellipse(img,(256,256),(110,80),0,0,360,(200,60,40),-1)
cv2.ellipse(img,(256,256),(20,150),0,180,360,(200,60,40),-1)
cv2.ellipse(img,(233,220),(10,20),0,0,360,(0,0,0),-1)
cv2.ellipse(img,(279,220),(10,20),0,0,360,(0,0,0),-1)
cv2.ellipse(img,(256,300),(80,34),0,0,360,(230,160,160),-1)
cv2.ellipse(img,(340,256),(30,50),0,0,360,(10,80,160),-1)
cv2.ellipse(img,(172,256),(30,50),0,0,360,(10,80,160),-1)
cv2.putText(img,"by okuoku",(100,430),cv2.FONT_HERSHEY_SIMPLEX,2,(0,0,0),4)
cv2.imshow("mizugorou",img)
cv2.imwrite("mizugorou.jpg",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

numpyの確認

In [61]:
pts = np.array([[350,220],[400,235],[350,250],[350,250]], np.int32)
print(pts)
pts = pts.reshape((-1,1,2))
print(pts)

[[350 220]
 [400 235]
 [350 250]
 [350 250]]
[[[350 220]]

 [[400 235]]

 [[350 250]]

 [[350 250]]]
